services:
  webhook-service:
    build:
      context: ./webhook-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - webhook-client
    environment:
      SERVER_PORT: 8080
      WEBHOOK_URL: http://webhook-client:8081/webhooks/notifications

  webhook-client:
    build:
      context: ./webhook-client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
