services:
  webhook-service:
    build:
      context: ./webhook-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - webhook-client-a
      - webhook-client-b
      - webhook-client-c
    environment:
      SERVER_PORT: 8080
      WEBHOOK_URLS: http://webhook-client-a:8081/webhooks/notifications,http://webhook-client-b:8081/webhooks/notifications,http://webhook-client-c:8081/webhooks/notifications

  webhook-client-a:
    build:
      context: ./webhook-client
      dockerfile: Dockerfile
    ports:
      - "18081:8081"
    environment:
      SERVER_PORT: 8081
      CLIENT_NAME: client-a

  webhook-client-b:
    build:
      context: ./webhook-client
      dockerfile: Dockerfile
    ports:
      - "18082:8081"
    environment:
      SERVER_PORT: 8081
      CLIENT_NAME: client-b

  webhook-client-c:
    build:
      context: ./webhook-client
      dockerfile: Dockerfile
    ports:
      - "18083:8081"
    environment:
      SERVER_PORT: 8081
      CLIENT_NAME: client-c
